# Hyprlauncher configuration
# Theme is defined in hyprtoolkit.conf (same directory)

general:grab_focus = 1

cache:enabled = 1

finders:default_finder = desktop
finders:desktop_prefix = ""
finders:unicode_prefix = "."
finders:math_prefix = "="
finders:font_prefix = "'"
finders:desktop_launch_prefix = uwsm app --
finders:desktop_terminal = kitty
finders:desktop_icons = 0

ui:window_size = 800 260
